TEMPLATE	=	app
QT		=	gui core xml widgets
CONFIG		+=	qt warn_on silent
DESTDIR		=	../../
INCLUDEPATH	=	../../src .
LIBS		=	-L../../ -lqsvte
TARGET          =       demo4
SOURCES		=	demo4.cpp
HEADERS		=	mainwindow4.h
